### ISSUE TITLE
Two versions of React Native source are stored

### ISSUE THREAD

**Issue by tommymchugh** [ReactExtensionManager/ReactExtensionManager#1]
For the pods file to be able to use React, pods must install React Native. However, the server fails using the pods version and _npm start_ must be run on a node module version. We should be able to have the REM-Podfile compile React from the React Native node module.

**Comment by tommymchugh** [comment]
It looks like the node module for react native does not include the podspec. I have to look into this to determine whether we can potentially change that, so rem can use just one version of react native source.

**Comment by ide** [comment]
We should also have a way to specify a copy of React Native that's not under node_modules. This would typically be a git checkout a React Native (e.g. a fork).

Just an idea - we could add a config entry to the main project's package.json file that specifies where to find React Native. (If unspecified, this path would default to `node_modules/react-native`.)

```
// package.json
{ ...
  "react-native-app": {
    "react-native-path": "../somewhere/anywhere/react-native"
  }
}
```

 REM would use this path when creating the entry for "React" in the REM-Podfile:

```
# REM-Podfile
pod 'React', :path => '../somewhere/anywhere/react-native'
```

**Comment by tommymchugh** [comment]
I agree. At this point if a path is not specified it should just add the cocoapods dependency, but in the future once we figure out the missing podspec file in node_modules/react-native we'll definitely switch to that.

**Comment by tommymchugh** [comment]
Just implemented the custom react native source in new issue #6 and closed it. Still looking into the one single react native source for server and cocoapods.

**Comment by oblador** [comment]
For the time being it works just getting the source from github directly instead which includes the podspec. 

```
  "dependencies": {
    "react-native": "https://github.com/facebook/react-native/archive/v0.3.4.tar.gz"
  }
```
