### ISSUE TITLE
NPM package name

### ISSUE THREAD

**Issue by tommymchugh** [ReactExtensionManager/ReactExtensionManager#2]
Should the package name be react-extension-manager or rem. This must be decided before publishing to npm.

**Comment by ide** [comment]
[rem is taken](https://www.npmjs.com/package/rem) so I'd go with react-extension-manager unless someone has a better name. I like rem for the binary name and there are already a couple of npm packages whose binaries don't match their package names anyway (jest-cli installs "jest", react-tools installs "jsx").

**Comment by tommymchugh** [comment]
I agree. Since thats good, I'll go and publish it and update the readme with install instructions from npm.
